version: '3'

services:
  front_prod:
    container_name: front_prod
    build:
      context: ./front
      dockerfile: prod.dockerfile
    volumes:
      - ./front:/app
    command: sh /app/bin/prod.entrypoint.sh
  nginx_prod:
    container_name: nginx_prod
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./front-end:/var/www/app
    links:
      - front_prod:front
    ports:
      - '8787:8787'

